version: '2'

services:

   eureka-server:
     image: microservice-eureka-demo
     hostname: eureka-server
     ports:
       - "8761:8761"

   config-service:
     image:  microservice-config-demo
     ports:
       - "8040:8040"

   service-a:
     image:  microservice-provider-demo
     links:
       - "eureka-server"
       - "config-service"


   service-b:
     image:  microservice-provider2-demo
     links:
       - "eureka-server"
       - "config-service"



   client-service:
     image:  microservice-client-demo
     ports:
       - "8765:8765"
     links:
       - "eureka-server"
       - "config-service"
       - "service-b"
       - "service-a"
